const productos = [
    {
        "id": 1,
        "codigo": "KU001",
        "nombre": "Peluche Kuromi Clásico",
        "marca": "Sanrio",
        "modelo": "30cm Sentada",
        "categoria": "Kuromi",
        "precio": 15990,
        "stock": 10,
        "descripcion": "Peluche oficial, 30 cm, felpa suave, ideal para coleccionar.",
        "imagen": "https://cl-cenco-pim-resizer.ecomm.cencosud.com/unsafe/adaptive-fit-in/3840x0/filters:quality(75)/prd-cl/product-medias/5fdbba58-0ae2-4fa4-9847-7b3d65e14191/MKA23T14QF/MKA23T14QF-1/1692235628607-MKA23T14QF-1-3.jpg"
    },
    {
        "id": 2,
        "codigo": "KU002",
        "nombre": "Mochila My Melody",
        "marca": "Sanrio",
        "modelo": "Escolar",
        "categoria": "Melody",
        "precio": 24990,
        "stock": 6,
        "descripcion": "Mochila con bolsillo frontal, parche bordado y correas ajustables.",
        "imagen": "https://http2.mlstatic.com/D_NQ_NP_857623-CBT113403054403_062026-O-mochila-my-melody-de-estilo-escolar-diario-con-funda-para-po.webp"
    },
    {
        "id": 3,
        "codigo": "KU003",
        "nombre": "Lampara Kuromi",
        "marca": "Sanrio",
        "modelo": "Lampara figura",
        "categoria": "Kuromi",
        "precio": 8990,
        "stock": 15,
        "descripcion": "Lampara recargable morada con figura de Kuromi",
        "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWq0uyEwLo3q93PR5CFkVGCevdQI9vXsSylUNwd7P6-ejFmjk6uhoP02lO&s=10"
    },
    {
        "id": 4,
        "codigo": "MG001",
        "nombre": "Manga One Piece Tomo 105",
        "marca": "Shueisha",
        "modelo": "Edición estándar",
        "categoria": "Mangas",
        "precio": 7990,
        "stock": 12,
        "descripcion": "Tapa blanda, papel ahuesado, edición en español.",
        "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUhn17yfiJGS-6tNXrEbKig5V9FBt2TyaNVSOZzpo5F-Lb__KpGPibyIM&s=10"
    },
    {
        "id": 15,
        "codigo": "SH003",
        "nombre": "Cómic Batman Edición Especial",
        "marca": "DC Comics",
        "modelo": "Tapa dura",
        "categoria": "Superhéroes",
        "precio": 12990,
        "stock": 7,
        "descripcion": "Portada variante, papel couché, 48 páginas.",
        "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAjQhbX8_Oe1mq8TwbZE1kcx43wPKqDCdZaamLElTy42iQwf-Anp6hQYqD&s=10"
    },
    {
        "id": 6,
        "codigo": "MG003",
        "nombre": "Mangas Dragon Ball",
        "marca": "Shueisha",
        "modelo": "Edición Kanzenban",
        "categoria": "Mangas",
        "precio": 8990,
        "stock": 9,
        "descripcion": "Mangas de Dragon Ball del 1-26, precio por unidad.",
        "imagen": "https://m.media-amazon.com/images/I/71VcSW3Q7PL._AC_UF1000,1000_QL80_.jpg"
    },
    {
        "id": 7,
        "codigo": "FG001",
        "nombre": "Figura Goku Super Saiyan",
        "marca": "Bandai",
        "modelo": "Figuarts Zero",
        "categoria": "Figuras",
        "precio": 32990,
        "stock": 5,
        "descripcion": "18 cm, pose dinámica, detalle de aura incluido.",
        "imagen": "img/figura-goku.jpg"
    },
    {
        "id": 8,
        "codigo": "FG002",
        "nombre": "Figura Naruto Uzumaki",
        "marca": "Banpresto",
        "modelo": "Vibration Stars",
        "categoria": "Figuras",
        "precio": 27990,
        "stock": 6,
        "descripcion": "16 cm, base incluida, edición coleccionable.",
        "imagen": "img/figura-naruto.jpg"
    },
    {
        "id": 9,
        "codigo": "SH001",
        "nombre": "Figura Batman Caballero de la Noche",
        "marca": "McFarlane Toys",
        "modelo": "DC Multiverse",
        "categoria": "Superhéroes",
        "precio": 34990,
        "stock": 4,
        "descripcion": "18 cm, 12 puntos de articulación, accesorios incluidos.",
        "imagen": "img/figura-batman.jpg"
    },
    {
        "id": 10,
        "codigo": "SH002",
        "nombre": "Figura Spider-Man Clásico",
        "marca": "Hasbro",
        "modelo": "Marvel Legends",
        "categoria": "Superhéroes",
        "precio": 29990,
        "stock": 7,
        "descripcion": "15 cm, pose de acción, detalle texturizado del traje.",
        "imagen": "img/figura-spiderman.jpg"
    },
    {
        "id": 11,
        "codigo": "PL001",
        "nombre": "Peluche Pikachu",
        "marca": "Pokémon Center",
        "modelo": "20cm",
        "categoria": "Peluches",
        "precio": 13990,
        "stock": 11,
        "descripcion": "Peluche oficial, tela suave, ideal para todas las edades.",
        "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwBdGG8Q_Vb_xv2AVFQ3eo5Er34HuzxYGyyOoNsbG6SfRX7CQhIU-k7Ro&s=10"
    },
    {
        "id": 12,
        "codigo": "PL002",
        "nombre": "Peluche Totoro",
        "marca": "Studio Ghibli",
        "modelo": "25cm",
        "categoria": "Peluches",
        "precio": 16990,
        "stock": 8,
        "descripcion": "Peluche gris con detalles bordados, relleno hipoalergénico.",
        "imagen": "https://meeq.com.au/cdn/shop/files/67315-3176710.jpg?v=1709776394"
    },
    {
        "id": 13,
        "codigo": "PO001",
        "nombre": "Póster Attack on Titan",
        "marca": "Genérico",
        "modelo": "A3",
        "categoria": "Anime",
        "precio": 5990,
        "stock": 20,
        "descripcion": "Impresión A3, acabado mate, viene con tubo protector.",
        "imagen": "img/poster-aot.jpg"
    },
    {
        "id": 14,
        "codigo": "AC001",
        "nombre": "Set Llaveros Chibi Anime Surtido",
        "marca": "Genérico",
        "modelo": "Pack x5",
        "categoria": "Accesorios",
        "precio": 9990,
        "stock": 18,
        "descripcion": "5 llaveros acrílicos de personajes variados, doble cara.",
        "imagen": "https://www.merakiimee.com/cdn/shop/files/IMG_20250111_114450.jpg?v=1741122614"
    },
    {
        "id": 15,
        "codigo": "SH003",
        "nombre": "Cómic Batman Edición Especial",
        "marca": "DC Comics",
        "modelo": "Tapa dura",
        "categoria": "Superhéroes",
        "precio": 12990,
        "stock": 7,
        "descripcion": "Portada variante, papel couché, 48 páginas.",
        "imagen": "img/comic-batman.jpg"
    }
];
