const productos = [
    {
        "id": 1,
        "codigo": "KU001",
        "nombre": "Peluche Kuromi Clásico",
        "marca": "Sanrio",
        "modelo": "30cm Sentada",
        "categoria": "Peluches",
        "precio": 15990,
        "stock": 10,
        "descripcion": "Peluche oficial, 30 cm, felpa suave, ideal para coleccionar.",
        "imagen": "https://cl-cenco-pim-resizer.ecomm.cencosud.com/unsafe/adaptive-fit-in/3840x0/filters:quality(75)/prd-cl/product-medias/5fdbba58-0ae2-4fa4-9847-7b3d65e14191/MKA23T14QF/MKA23T14QF-1/1692235628607-MKA23T14QF-1-3.jpg"
    },
    {
        "id": 2,
        "codigo": "KU002",
        "nombre": "Mochila My Melody",
        "marca": "Sanrio",
        "modelo": "Escolar",
        "categoria": "Accesorios",
        "precio": 24990,
        "stock": 6,
        "descripcion": "Mochila con bolsillo frontal, parche bordado y correas ajustables.",
        "imagen": "https://http2.mlstatic.com/D_NQ_NP_857623-CBT113403054403_062026-O-mochila-my-melody-de-estilo-escolar-diario-con-funda-para-po.webp"
    },
    {
        "id": 3,
        "codigo": "KU003",
        "nombre": "Lampara Kuromi",
        "marca": "Sanrio",
        "modelo": "Electronica",
        "categoria": "Kuromi",
        "precio": 8990,
        "stock": 15,
        "descripcion": "Lampara recargable morada con figura de Kuromi.",
        "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWq0uyEwLo3q93PR5CFkVGCevdQI9vXsSylUNwd7P6-ejFmjk6uhoP02lO&s=10"
    },
    {
        "id": 4,
        "codigo": "MG001",
        "nombre": "Manga One Piece Tomo 105",
        "marca": "Shueisha",
        "modelo": "Edición estándar",
        "categoria": "Mangas",
        "precio": 7990,
        "stock": 12,
        "descripcion": "Tapa blanda, papel ahuesado, edición en español.",
        "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUhn17yfiJGS-6tNXrEbKig5V9FBt2TyaNVSOZzpo5F-Lb__KpGPibyIM&s=10"
    },
    {
        "id": 5,
        "codigo": "SH003",
        "nombre": "Cómic Batman Edición Especial",
        "marca": "DC Comics",
        "modelo": "Tapa dura",
        "categoria": "Superhéroes",
        "precio": 12990,
        "stock": 7,
        "descripcion": "Portada variante, papel couché, 48 páginas.",
        "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAjQhbX8_Oe1mq8TwbZE1kcx43wPKqDCdZaamLElTy42iQwf-Anp6hQYqD&s=10"
    },
    {
        "id": 6,
        "codigo": "MG003",
        "nombre": "Mangas Dragon Ball",
        "marca": "Shueisha",
        "modelo": "Edición Kanzenban",
        "categoria": "Mangas",
        "precio": 31990,
        "stock": 3,
        "descripcion": "Mangas de Dragon Ball BOX 1-26 PACK COLECCION COMPLETA.",
        "imagen": "https://m.media-amazon.com/images/I/71VcSW3Q7PL._AC_UF1000,1000_QL80_.jpg"
    },
    {
        "id": 7,
        "codigo": "FG001",
        "nombre": "Figura Goku Super Saiyan",
        "marca": "Bandai",
        "modelo": "Figuarts Zero",
        "categoria": "Figuras",
        "precio": 32990,
        "stock": 5,
        "descripcion": "18 cm, pose dinámica, detalle de aura incluido.",
        "imagen": "https://image.made-in-china.com/202f0j00FdLqHUtrbMkD/Wholesale-Japanese-Action-Figures-Toys-Dragon-Ball-Z-Super-Saiyan-Goku-Statues-Base-Luminescence-Anime-Figure.webp"
    },
    {
        "id": 8,
        "codigo": "FG002",
        "nombre": "Figura Naruto Uzumaki",
        "marca": "Banpresto",
        "modelo": "Vibration Stars",
        "categoria": "Figuras",
        "precio": 27990,
        "stock": 6,
        "descripcion": "16 cm, base incluida, edición coleccionable.",
        "imagen": "https://dojiw2m9tvv09.cloudfront.net/68889/product/d9a5e824-3cd8-4efd-a746-7cda57704957-3f68a38c9001cecd2c78f5f34f2a56f06493.png"
    },
    {
        "id": 9,
        "codigo": "SH001",
        "nombre": "Figura Batman Patito",
        "marca": "McFarlane Toys",
        "modelo": "DC Multiverse",
        "categoria": "Superhéroes",
        "precio": 5990,
        "stock": 4,
        "descripcion": "Figura patito de Batman, edicion exclusiva.",
        "imagen": "https://tubbz.com/cdn/shop/files/DCComics_Bundle1_TBZUK.jpg?v=1780408205&width=500"
    },
    {
        "id": 10,
        "codigo": "SH002",
        "nombre": "Figura Spider-Man Clásico",
        "marca": "Hasbro",
        "modelo": "Marvel Legends",
        "categoria": "Superhéroes",
        "precio": 25990,
        "stock": 7,
        "descripcion": "15 cm, pose de acción, detalle texturizado del traje.",
        "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7ygD1UPVtHp2rG3xdkkJuCfYmGGwoMm9DYeWFqwf4CPpzF6Xrhfrxjrcb&s=10"
    },
    {
        "id": 11,
        "codigo": "PL001",
        "nombre": "Peluche Pikachu",
        "marca": "Pokémon Center",
        "modelo": "20cm",
        "categoria": "Peluches",
        "precio": 13990,
        "stock": 11,
        "descripcion": "Peluche oficial, tela suave, ideal para todas las edades.",
        "imagen":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfx00banVmPyZdx_76OZlT2XnxUeKERLKglV3Zjfit-Q&s=10"
    },
    {
        "id": 12,
        "codigo": "PL002",
        "nombre": "Peluche Stitch",
        "marca": "Disney",
        "modelo": "25cm",
        "categoria": "Peluches",
        "precio": 16990,
        "stock": 8,
        "descripcion": "Peluche Stitch azul tierno.",
        "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVgqldhiHAJmzAOaiEHHkGNtbN_0Cbrxbu11v6o6yHAhOPJNIE0CTJ9Ro&s=10"
    },
    {
        "id": 13,
        "codigo": "PO001",
        "nombre": "Cartas Pokemon",
        "marca": "Pokemon",
        "modelo": "Cartas",
        "categoria": "Anime",
        "precio": 8990,
        "stock": 20,
        "descripcion": "Sobre de cartas Pokemon, producto original.",
        "imagen": "https://elreinodelosduelos.cl/wp-content/uploads/2026/06/PRODUCTO-WEB-24.jpg"
    },
    {
        "id": 14,
        "codigo": "AC001",
        "nombre": "Audifonos Minecraft",
        "marca": "Genérico",
        "modelo": "Audifonos",
        "categoria": "Electronica",
        "precio": 9990,
        "stock": 18,
        "descripcion": "Audifonos inalambricos, color verde, bateria de larga duracion.",
        "imagen": "https://http2.mlstatic.com/D_NQ_NP_675197-CBT79731390564_102024-O.webp"
    },
    {
        "id": 15,
        "codigo": "SH003",
        "nombre": "Lego Batman Mini",
        "marca": "LEGO",
        "modelo": "Bloques de construccion",
        "categoria": "Superhéroes",
        "precio": 12990,
        "stock": 7,
        "descripcion": "Lego Batman de 200 piezas.",
        "imagen": "https://www.lego.com/cdn/cs/set/assets/blt7ccd17b931042874/40726_Prod.png?fit=bounds&format=jpg&quality=80&width=1500&height=1500&dpr=1"
    },
    {
        "id": 16,
        "codigo": "EA001",
        "nombre": "Colonia Batman",
        "marca": "Genérico",
        "modelo": "100 mL",
        "categoria": "SuperHeroes",
        "precio": 4990,
        "stock": 20,
        "descripcion": "Eau de toilet de Batman.",
        "imagen": "https://i.makeup.es/2/2i/2i3dvuwomovg.jpg"
    },
    {
        "id": 17,
        "codigo": "LL034",
        "nombre": "Llaveros Stitch",
        "marca": "Genérico",
        "modelo": "Llaveros",
        "categoria": "Accesorios",
        "precio": 2990,
        "stock": 23,
        "descripcion": "Llaveros Stitch para compartir.",
        "imagen": "https://dcdn-us.mitiendanube.com/stores/954/283/products/llavero-stitch-amor-c40aca245b45c2f7f717262654447723-640-0.webp"
    },
    {
        "id": 18,
        "codigo": "FP345",
        "nombre": "Funko Pop Pennywise",
        "marca": "Funko Pop",
        "modelo": "Funko POP",
        "categoria": "Juguetes",
        "precio": 9990,
        "stock": 12,
        "descripcion": "Funko Pop Pennywise IT, edicion basica.",
        "imagen": "https://i5.walmartimages.com/seo/Funko-POP-Movies-IT-Pennywise_1093cecb-8c03-4c20-8fd6-9494b59a5ac4.4e57a75179c82b3c0ef27341810a09f8.jpeg"
    },
    {
        "id": 19,
        "codigo": "FP346",
        "nombre": "Funko Pop Groot",
        "marca": "Funko Pop",
        "modelo": "Funko POP",
        "categoria": "Juguetes",
        "precio": 9990,
        "stock": 19,
        "descripcion": "Funko Pop Groot Guardianes De La Galexia, edicion basica.",
        "imagen": "https://thebrandsclub.com/cdn/shop/files/13230_gotg2_groot_pop_glam_hires-1c06712d-6455-416f-89b4-23a4cdb29aa7_27a984cf-ceab-4543-a3d3-aea36cbbbee5.jpg?v=1769789649"
    },
    {
        "id": 20,
        "codigo": "FP348",
        "nombre": "Funko Pop Time Wizard",
        "marca": "Funko Pop",
        "modelo": "Funko POP",
        "categoria": "Juguetes",
        "precio": 9990,
        "stock": 15,
        "descripcion": "Funko Pop Time Wizard YU-GI-OH!, edicion basica.",
        "imagen": "https://www.weplay.cl/pub/media/catalog/product/cache/3f1b140c3c9f36fbf6b01dffb521c246/8/8/889698720656-02.jpg"
    },
    {
        "id": 21,
        "codigo": "MQ8756",
        "nombre": "Set Maquillaje The Simpsons",
        "marca": "MAC",
        "modelo": "Set Maquillaje",
        "categoria": "Maquillaje",
        "precio": 29990,
        "stock": 14,
        "descripcion": "Set maquillaje: Sombra, Rubor en polvo, Paleta de contorno e iluminadores y labial. Edicion limitada.",
        "imagen": "https://www.mercadonegro.pe/wp-content/uploads/2021/11/cosmeticos-simpson.jpg"
    },
    {
        "id": 22,
        "codigo": "WE138",
        "nombre": "Botella The Simpsons",
        "marca": "Generico",
        "modelo": "500 mL",
        "categoria": "Accesorios",
        "precio": 5990,
        "stock": 22,
        "descripcion": "Botella metalica Homero Simpson.",
        "imagen": "https://storline.com/3530977-large_default/botella-termo-acero-inoxidable-515-ml-simpsons-homer.jpg"
    },
    {
        "id": 23,
        "codigo": "MM096",
        "nombre": "Monopoly The Simpsons",
        "marca": "Hasbro",
        "modelo": "Monopoly Juego",
        "categoria": "Juguetes",
        "precio": 12990,
        "stock": 16,
        "descripcion": "Monopoly The Simpsons, edicion Limitada.",
        "imagen": "https://sm.ign.com/ign_latam/screenshot/default/81pedx5vzwl-ac-sl1500_gasp.jpg"
    },
    {
        "id": 24,
        "codigo": "LP256",
        "nombre": "Lampara Minecraft",
        "marca": "Generico",
        "modelo": "Lampara",
        "categoria": "Electronica",
        "precio": 12990,
        "stock": 10,
        "descripcion": "Lampara pocion Minecraft, recargable, incluye USB.",
        "imagen": "https://http2.mlstatic.com/D_Q_NP_920744-CBT81446330011_122024-O.webp"
    },
    {
        "id": 25,
        "codigo": "OP647",
        "nombre": "Figura Hollow Knight",
        "marca": "Generico",
        "modelo": "Figura",
        "categoria": "Figura",
        "precio": 14990,
        "stock": 7,
        "descripcion": "Figura Hollow Knight 27 cm.",
        "imagen": "https://ae-pic-a1.aliexpress-media.com/kf/S6234290a946d4de89d532c77b5e9d7e1G.jpg"
    },
    {
        "id": 26,
        "codigo": "LP459",
        "nombre": "Hollow Knigth Edicion Coleccionista",
        "marca": "FANGAMER",
        "modelo": "Juegos",
        "categoria": "Electronica",
        "precio": 159990,
        "stock": 2,
        "descripcion": "Incluye todos los accesorios fisicos + digital edicion coleccionable.",
        "imagen": "https://cdn.shopify.com/s/files/1/0745/0243/9197/files/product_HK_CE_photo_switch_cleaningcloth2.webp?v=1752532962"
    },
    {
        "id": 27,
        "codigo": "GW105",
        "nombre": "God Of War Edicion Coleccionable",
        "marca": "Sony",
        "modelo": "Edicion Coleccionista",
        "categoria": "Juegos",
        "precio": 169990,
        "stock": 2,
        "descripcion": "Incluye todos los accesorios fisicos + digital edicion coleccionable.",
        "imagen": "https://m.media-amazon.com/images/I/91Ij9hf-4+L.jpg"
    },
    {
        "id": 28,
        "codigo": "UP184",
        "nombre": "Manga Uzumaki",
        "marca": "Planeta Comic",
        "modelo": "Manga",
        "categoria": "Mangas",
        "precio": 11990,
        "stock": 13,
        "descripcion": "Manga Junji Ito UZUMAKI, tapa dura.",
        "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmh35u0seaR2Y0AcJhKqKntF37wxKCIERool4jfsBvThGq34Vz4G4XNAw&s=10"
    },
    {
        "id": 29,
        "codigo": "CB492",
        "nombre": "Comic Batman vs Superman",
        "marca": "DC Comics",
        "modelo": "Comic",
        "categoria": "SuperHeroes",
        "precio": 12990,
        "stock": 17,
        "descripcion": "Comic Batman VS Superman, Tapa dura.",
        "imagen": "https://u-mercari-images.mercdn.net/photos/m22404587984_1.jpg?width=2560&quality=75&_=1769972381"
    },
    {
        "id": 30,
        "codigo": "MB537",
        "nombre": "BATMANGA",
        "marca": "Panini",
        "modelo": "SuperHeroes",
        "categoria": "Mangas",
        "precio": 13990,
        "stock": 11,
        "descripcion": "BATMANGA volumen 1.",
        "imagen": "https://cdnx.jumpseller.com/shazam-online/image/67190244/batmanga_01.jpg?1756836083"
    },
    {
        "id": 31,
        "codigo": "FG354",
        "nombre": "Juego de mesa de Batman",
        "marca": " GEN X",
        "modelo": " Juguetes",
        "categoria": "Cartas",
        "precio": 10990,
        "stock": 7,
        "descripcion": "Juego de mesa de Batman: El regreso del caballero oscuro.",
        "imagen": "https://www.updown.cl/wp-content/uploads/2025/10/original-219.jpeg"
    },
    {
        "id": 32,
        "codigo": "CM267",
        "nombre": "Cartas Magic",
        "marca": "Wizards of the Coast",
        "modelo": "Commander",
        "categoria": "Cartas",
        "precio": 30990,
        "stock": 5,
        "descripcion": "Juego de cartas MAGIC, Mazo Commander Calling All Angels. 100 cartas multijugador",
        "imagen": "https://elreinodelosduelos.cl/wp-content/uploads/2026/08/PRODUCTO-WEB1-3-3-768x960.jpg.webp"
    },
    {
        "id": 33,
        "codigo": "AT385",
        "nombre": "Jugeo de mesa Attack On Titan",
        "marca": "Cryptozoic Entertainment",
        "modelo": "Juego de mesa",
        "categoria": "Juguetes",
        "precio": 32990,
        "stock": 4,
        "descripcion": "Attack on Titan: La última resistencia. Juego de mesa asimétrico y semi-cooperativo basado en el anime.",
        "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfVjFLS9pdhMNDciJbqCgczYOLfy0wcaOtsvncXPL0oXMdF4NIotsEnYHf&s=10"
    }
    
];
