const productos = [
    {
        "id": 1,
        "codigo": "KU001",
        "nombre": "Peluche Kuromi Clásico",
        "marca": "Sanrio",
        "modelo": "30cm Sentada",
        "categoria": "Kuromi",
        "precio": 15990,
        "stock": 10,
        "descripcion": "Peluche oficial, 30 cm, felpa suave, ideal para coleccionar.",
        "imagen": "https://media.falabella.com/falabellaCL/147508046_01/w=1500,h=1500,fit=cover"
    },
    {
        "id": 2,
        "codigo": "KU002",
        "nombre": "Mochila Kuromi Luna Negra",
        "marca": "Sanrio",
        "modelo": "Escolar",
        "categoria": "Kuromi",
        "precio": 24990,
        "stock": 6,
        "descripcion": "Mochila con bolsillo frontal, parche bordado y correas ajustables.",
        "imagen": "img/kuromi-mochila.jpg"
    },
    {
        "id": 3,
        "codigo": "KU003",
        "nombre": "Taza Kuromi Calavera",
        "marca": "Sanrio",
        "modelo": "350ml",
        "categoria": "Kuromi",
        "precio": 8990,
        "stock": 15,
        "descripcion": "Taza de cerámica, apta para microondas, diseño exclusivo.",
        "imagen": "img/kuromi-taza.jpg"
    },
    {
        "id": 4,
        "codigo": "MG001",
        "nombre": "Manga One Piece Tomo 105",
        "marca": "Shueisha",
        "modelo": "Edición estándar",
        "categoria": "Mangas",
        "precio": 7990,
        "stock": 12,
        "descripcion": "Tapa blanda, papel ahuesado, edición en español.",
        "imagen": "img/manga-onepiece.jpg"
    },
    {
        "id": 5,
        "codigo": "MG002",
        "nombre": "Manga Naruto Tomo 1",
        "marca": "Shueisha",
        "modelo": "Edición estándar",
        "categoria": "Mangas",
        "precio": 7490,
        "stock": 14,
        "descripcion": "Primer tomo de la serie, ideal para empezar la colección.",
        "imagen": "img/manga-naruto.jpg"
    },
    {
        "id": 6,
        "codigo": "MG003",
        "nombre": "Manga Dragon Ball Tomo 1",
        "marca": "Shueisha",
        "modelo": "Edición Kanzenban",
        "categoria": "Mangas",
        "precio": 8990,
        "stock": 9,
        "descripcion": "Edición de lujo con tapa dura y páginas a color.",
        "imagen": "img/manga-dragonball.jpg"
    },
    {
        "id": 7,
        "codigo": "FG001",
        "nombre": "Figura Goku Super Saiyan",
        "marca": "Bandai",
        "modelo": "Figuarts Zero",
        "categoria": "Figuras",
        "precio": 32990,
        "stock": 5,
        "descripcion": "18 cm, pose dinámica, detalle de aura incluido.",
        "imagen": "img/figura-goku.jpg"
    },
    {
        "id": 8,
        "codigo": "FG002",
        "nombre": "Figura Naruto Uzumaki",
        "marca": "Banpresto",
        "modelo": "Vibration Stars",
        "categoria": "Figuras",
        "precio": 27990,
        "stock": 6,
        "descripcion": "16 cm, base incluida, edición coleccionable.",
        "imagen": "img/figura-naruto.jpg"
    },
    {
        "id": 9,
        "codigo": "SH001",
        "nombre": "Figura Batman Caballero de la Noche",
        "marca": "McFarlane Toys",
        "modelo": "DC Multiverse",
        "categoria": "Superhéroes",
        "precio": 34990,
        "stock": 4,
        "descripcion": "18 cm, 12 puntos de articulación, accesorios incluidos.",
        "imagen": "img/figura-batman.jpg"
    },
    {
        "id": 10,
        "codigo": "SH002",
        "nombre": "Figura Spider-Man Clásico",
        "marca": "Hasbro",
        "modelo": "Marvel Legends",
        "categoria": "Superhéroes",
        "precio": 29990,
        "stock": 7,
        "descripcion": "15 cm, pose de acción, detalle texturizado del traje.",
        "imagen": "img/figura-spiderman.jpg"
    },
    {
        "id": 11,
        "codigo": "PL001",
        "nombre": "Peluche Pikachu",
        "marca": "Pokémon Center",
        "modelo": "20cm",
        "categoria": "Peluches",
        "precio": 13990,
        "stock": 11,
        "descripcion": "Peluche oficial, tela suave, ideal para todas las edades.",
        "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwBdGG8Q_Vb_xv2AVFQ3eo5Er34HuzxYGyyOoNsbG6SfRX7CQhIU-k7Ro&s=10"
    },
    {
        "id": 12,
        "codigo": "PL002",
        "nombre": "Peluche Totoro",
        "marca": "Studio Ghibli",
        "modelo": "25cm",
        "categoria": "Peluches",
        "precio": 16990,
        "stock": 8,
        "descripcion": "Peluche gris con detalles bordados, relleno hipoalergénico.",
        "imagen": "https://meeq.com.au/cdn/shop/files/67315-3176710.jpg?v=1709776394"
    },
    {
        "id": 13,
        "codigo": "PO001",
        "nombre": "Póster Attack on Titan",
        "marca": "Genérico",
        "modelo": "A3",
        "categoria": "Anime",
        "precio": 5990,
        "stock": 20,
        "descripcion": "Impresión A3, acabado mate, viene con tubo protector.",
        "imagen": "img/poster-aot.jpg"
    },
    {
        "id": 14,
        "codigo": "AC001",
        "nombre": "Set Llaveros Chibi Anime Surtido",
        "marca": "Genérico",
        "modelo": "Pack x5",
        "categoria": "Accesorios",
        "precio": 9990,
        "stock": 18,
        "descripcion": "5 llaveros acrílicos de personajes variados, doble cara.",
        "imagen": "https://www.merakiimee.com/cdn/shop/files/IMG_20250111_114450.jpg?v=1741122614"
    },
    {
        "id": 15,
        "codigo": "SH003",
        "nombre": "Cómic Batman Edición Especial",
        "marca": "DC Comics",
        "modelo": "Tapa dura",
        "categoria": "Superhéroes",
        "precio": 12990,
        "stock": 7,
        "descripcion": "Portada variante, papel couché, 48 páginas.",
        "imagen": "img/comic-batman.jpg"
    }
];
